name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: w-types.tex
      - name: stash pdf
        run: |
          mv w-types.pdf $HOME
      - name: checkout document_releases branch
        uses: actions/checkout@v2
        with:
          ref: document_releases
      - name: commit pdf
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mv $HOME/w-types.pdf $(pwd) # bring it back 
          git add w-types.pdf
          git commit -m "updated document"
      - name:  push pdf
        uses: ad-m/github-push-action@v0.5.0
        with: 
          branch: document_releases 
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
